<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240426082022 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE parchment');
        $this->addSql('ALTER TABLE api_token ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE api_token ALTER expira TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN api_token.expira IS \'\'');
        $this->addSql('ALTER TABLE asiento ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE boleto ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE boleto_log ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE book ALTER id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN book.id IS \'\'');
        $this->addSql('ALTER TABLE bookmark ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE bookmark ALTER book_id TYPE UUID');
        $this->addSql('ALTER TABLE bookmark ALTER bookmarked_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN bookmark.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN bookmark.book_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN bookmark.bookmarked_at IS \'\'');
        $this->addSql('ALTER TABLE bus ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE cliente ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE empresa ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE factura ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE fdn ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE localidad ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE pais ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE parada_intermedia ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE permiso ADD nombre VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE permiso ADD nota TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE permiso ADD status SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE permiso ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE piloto ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE recorrido_asiento_precio ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE review ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE review ALTER book_id TYPE UUID');
        $this->addSql('ALTER TABLE review ALTER published_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN review.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN review.book_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN review.published_at IS \'\'');
        $this->addSql('ALTER TABLE salida ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE salida_log ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE "user" ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE venta ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('CREATE TABLE parchment (id UUID NOT NULL, title VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN parchment.id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE salida_log ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE pais ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE bus ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE localidad ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE recorrido_asiento_precio ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE cliente ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE asiento ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE "user" ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE review ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE review ALTER published_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE review ALTER book_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN review.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN review.published_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN review.book_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE book ALTER id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN book.id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE bookmark ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE bookmark ALTER bookmarked_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bookmark ALTER book_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN bookmark.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN bookmark.bookmarked_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN bookmark.book_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE factura ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE boleto_log ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE fdn ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE piloto ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE venta ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE salida ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE api_token ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE api_token ALTER expira TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN api_token.expira IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE parada_intermedia ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE boleto ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE permiso DROP nombre');
        $this->addSql('ALTER TABLE permiso DROP nota');
        $this->addSql('ALTER TABLE permiso DROP status');
        $this->addSql('ALTER TABLE permiso ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE empresa ALTER id DROP IDENTITY');
    }
}
